/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/components/Skrillex.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Skrillex.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SKRILLEX_new_1.geometry} material={materials._Metal_Corrogated_Shiny_7} />
        <mesh geometry={nodes.SKRILLEX_new_2.geometry} material={materials.Color_M08} />
        <mesh geometry={nodes.SKRILLEX_new_3.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.SKRILLEX_new_4.geometry} material={materials.Color_M09} />
        <mesh geometry={nodes.SKRILLEX_new_5.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.SKRILLEX_new_6.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.SKRILLEX_new_7.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.SKRILLEX_new_8.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.SKRILLEX_new_9.geometry} material={materials._Crushed_Rock_Gravel_1} />
        <mesh geometry={nodes.SKRILLEX_new_10.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.SKRILLEX_new_11.geometry} material={materials.Color_M00} />
        <mesh geometry={nodes.SKRILLEX_new_12.geometry} material={materials._Color_A01_1} />
        <mesh geometry={nodes.SKRILLEX_new_13.geometry} material={materials.Metal_Steel_Textured} />
        <mesh geometry={nodes.SKRILLEX_new_14.geometry} material={materials.Metal_Rough} />
        <mesh geometry={nodes.SKRILLEX_new_15.geometry} material={materials.Metal_Corrogated_Shiny} />
        <mesh geometry={nodes.SKRILLEX_new_16.geometry} material={materials._Metal_Corrogated_Shiny_4} />
        <mesh geometry={nodes.SKRILLEX_new_17.geometry} material={materials._Metal_Corrogated_Shiny_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Skrillex.glb')
