/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Skrillex_.glb --draco ./public/draco/ --output src/components/Skrillex_.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Skrillex_.glb', './public/draco/')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SKRILLEX_new.geometry} material={materials._Metal_Corrogated_Shiny_7} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Skrillex_.glb')
