/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Skrillex_.glb --draco ./public/draco/ --output src/components/Skrillex_.jsx 
*/

import React, { useEffect } from 'react'; // Import useEffect
import { useGLTF } from '@react-three/drei';

export function Model({ onLoad, ...props }) { 
  const { nodes, materials } = useGLTF('/Skrillex_.glb', '/draco/');

  // Call onLoad once the component has successfully mounted and loaded the model
  useEffect(() => {
    if (nodes && materials && typeof onLoad === 'function') {
      onLoad(); 
    }
  }, [nodes, materials, onLoad]); // Depend on nodes and materials

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SKRILLEX_new.geometry} material={materials._Metal_Corrogated_Shiny_7} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload('/Skrillex_.glb');

